### ISSUE TITLE
0.7.0 Release Checklist

### ISSUE THREAD

**Issue by matthewp** [bitovi/steal#337]
Documenting how I will release 0.7.0 to make sure everything is lined up:

* [x] system-bower 0.1.0 (tag)
* [x] system-npm 0.1.0 (tag and publish)
* [x] transpile 0.5.0 (tag and publish)
* [x] steal 0.7.0 (tag and publish)
  * [x] system-bower dep (bower.json)
  * [x] system-npm dep (package.json)
* [x] steal-tools 0.7.0 (tag and publish)
  * [x] steal dep (bower.json and package.json)
  * [x] transpile dep (package.json)
* [x] Regenerate and publish documentation

**Comment by matthewp** [comment]
Done.

**Comment by matthewp** [comment]
Note for next time, also update the changelog.
